### ISSUE TITLE
NoSuchMethodError for setCreateOptionalGetters on Build

### ISSUE THREAD

**Issue by ajunB7** [davidmc24/gradle-avro-plugin#197]
**Describe the bug**

Trying to build for the first time in a brand new project. Hitting a `NoSuchMethodError` on `setCreateOptionalGetters` at `GenerateAvroJavaTask.compile(GenerateAvroJavaTask.java:325)`. 

**To Reproduce**

1. 
```
plugins {
    id 'java'
    id 'com.github.davidmc24.gradle.plugin.avro' version '1.3.0'
}

dependencies {
    api 'org.apache.avro:avro:1.11.0'
}
```
3. `shared->src->main->avro->projectname->Envelope.avsc`
4. `./gradlew build`
5. See error

```
2022-04-27T17:07:53.120-0400 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NoSuchMethodError: org.apache.avro.compiler.specific.SpecificCompiler.setCreateOptionalGetters(Z)V
2022-04-27T17:07:53.120-0400 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.davidmc24.gradle.plugin.avro.GenerateAvroJavaTask.compile(GenerateAvroJavaTask.java:325)
2022-04-27T17:07:53.120-0400 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.davidmc24.gradle.plugin.avro.GenerateAvroJavaTask.processSchemaFiles(GenerateAvroJavaTask.java:309)
2022-04-27T17:07:53.120-0400 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.davidmc24.gradle.plugin.avro.GenerateAvroJavaTask.processFiles(GenerateAvroJavaTask.java:280)
2022-04-27T17:07:53.121-0400 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.github.davidmc24.gradle.plugin.avro.GenerateAvroJavaTask.process(GenerateAvroJavaTask.java:265)
2022-04-27T17:07:53.121-0400 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**Expected behavior**

Not sure why only setCreateOptionalGetters is causing problems

**Environment (please complete the following information):**
 - Gradle Version: Gradle 7.1.1
 - Apache Avro Version: 1.11.0
 - Gradle-Avro Plugin Version: 1.3.0
 - Java Version: Java 11.0.13
 - OS: MacOS 12.0.1

**Additional context**

**Comment by ajunB7** [comment]
Nevermind its been a long day. It seems I had another reference to this plugin but a different version. Deleting that causes it to work as expected.
